# Generated by Django 3.1.2 on 2020-10-31 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coords', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, unique=True)),
                ('tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=8)),
            ],
        ),
    ]
