# Generated by Django 3.1.3 on 2020-11-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medfacility',
            name='address',
            field=models.CharField(default='Avenida 25 de Abril', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
