# Generated by Django 3.1.2 on 2020-10-24 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medfacility',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True),
        ),
    ]
