version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_mysql_calendar
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: es2020
      MYSQL_DATABASE: CalendarUsers
    ports:
      - 9094:3306
    expose:
        - "3306"
    
  adminer:
    image: adminer
    container_name: db_mysql_adminer
    restart: always
    ports:
      - 9093:8080
    expose:
        - "8080"
    
    
  calendar_golangApp:
    container_name: calendar_service
    image: calendarapp:latest
    ports:
      - 9091:9091
    depends_on:
      - db



  
