version: "3"
   
volumes:
  postgis-data:

services:
  directory_db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=geomed
      - POSTGRES_USER=postgis
      - POSTGRES_PASS=postgis
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  directory_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - directory_db

